name: Check directory structure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-lts

    steps:
    - uses: actions/checkout@v3

    - name: Check directory structure
      run: make check
